### ISSUE TITLE
Doesn't seem to run properly on Windows 10

### ISSUE THREAD

**Issue by emmorts** [ritz078/snape#20]
The app starts up with a blank screen, as well as doesn't appear in the task bar.

I'm using Windows 10, with a Creator's update.

![image](https://cloud.githubusercontent.com/assets/3183641/26604887/7db5f1a4-4594-11e7-9ac4-bc4ac84672ce.png)

**Comment by ritz078** [comment]
Hi @emmorts ,

Can you test and let me know if it works now ? Below is the latest build https://github.com/ritz078/snape/releases/download/v0.1.6/snape-Setup-0.1.6.exe

**Comment by emmorts** [comment]
It seems that it did help, as I can see the content properly now. The only thing that still seems missing is the task bar item.

**Comment by ritz078** [comment]
Can you post the screenshot. I am asking as I don't have a windows system to test. Thanks.

**Comment by emmorts** [comment]
There we go.
![image](https://cloud.githubusercontent.com/assets/3183641/26762570/3ef10082-494d-11e7-9348-fd814449e0af.png)

One additional thing, perhaps it'd be best to create a shortcut on desktop, as right now it's rather tedious to find it lying in AppData.

**Comment by ritz078** [comment]
Agreed. #22
