### ISSUE TITLE
search always return 500

### ISSUE THREAD

**Issue by FrancescoCioria** [ritz078/snape#33]
I tried multiple searches (including "lord of the rings") but I always get this error:

![image](https://user-images.githubusercontent.com/4029499/29841027-3e374fb6-8d04-11e7-86da-21b5fe71cbe4.png)

**Comment by ritz078** [comment]
That may be the case if cloudflare has blacklisted your IP. That should be temporary or a VPN can solve that issue.

**Comment by FrancescoCioria** [comment]
I'm trying to investigate by running the app locally, but when run with `yarn start` it's extremely slow, do you know why?

**Comment by FrancescoCioria** [comment]
nevermind, after it fakely re-downloads the torrents in the download page it starts to go fast again.
it's much slower at doing so than the official app (which also lags until this process is complete) probably because it's running in dev mode.

I'll update you here when If I find out more about the returned `500`

**Comment by ritz078** [comment]
It is supposed to be slow in dev mode because the files are compiled on the fly whereas in production the static files are created in advance.

**Comment by ritz078** [comment]
@FrancescoCioria any update ?

**Comment by FrancescoCioria** [comment]
I couldn't find out the issue and after a couple of days it began to work again so I stopped worrying about it

**Comment by ritz078** [comment]
I think that may have been a CloudFlare blocking issue due to a lot of requests. Good to hear that its working fine for you.
