### ISSUE TITLE
Movie sound is not working?

### ISSUE THREAD

**Issue by MSZ991** [ritz078/snape#41]

**Comment by ritz078** [comment]
The reason for sound not working can be that chrome doesn't support the audio format that is encoded in the movie. In that case, you should use the "play with vlc" feature and you can hear the audio.

**Comment by MSZ991** [comment]
Ritesh Bro!!! VLC option is not available on it.I have attached below screenshot.It was working fine earlier.But now its giving error.Please let me know how to enable VLC option. I am using the latest version.
Thank you
<img width="984" alt="Screen Shot 2019-06-15 at 3 15 48 AM" src="https://user-images.githubusercontent.com/14855029/59541791-576b0b00-8f1c-11e9-9e68-3121220fd30a.png">

**Comment by ritz078** [comment]
You have to install VLC separately to enable it.

**Comment by MSZ991** [comment]
I have already installed VLC. Its not working.
